# Generated by Django 3.0.6 on 2020-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_charity',
            field=models.BooleanField(default=True),
        ),
    ]
