# Generated by Django 3.0.6 on 2020-06-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profapp', '0003_auto_20200624_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='story_image',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
