# Generated by Django 3.0.6 on 2020-07-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profapp', '0006_auto_20200630_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
